### ISSUE TITLE
[Android Bootcamp] Project 2: Google Image Search - Ready for Review

### ISSUE THREAD

**Issue by paulinar** [paulinar/google-image-search#1]
My app is complete, please review! /cc @codepathreview @codepath

Also had a few questions:
- Some grid tiles would not fill with images upon loading (see 'giraffes' query in icecap gif). Any reason why that may be happening? 
- With regards to organizing source files, was it appropriate of me to put my EndlessScrollListener and TouchImageView classes into the helpers package?

**Comment by codepathreview** [comment]
:+1: Excellent work, Paulina!! 

Answers to your questions:
- May be the response for them did not come through? Got to debug more on this.
- You have correctly placed it in `helpers` package. 

Few notes after checking the code:
- Good to see you used a filters object to represent the filters to apply to the query
- Consider using `Parcelable` instead of `Serializable` 
- Properly used spinners (with populated values) to allow users to select filters
- Great job implementing `TouchImageView` and `StaggeredGridView`
- Consider adding the ability to [share an image](http://guides.codepath.com/android/Sharing-Content-with-Intents). This is an important learning for this assignment even though it's optional.
- Nice to see you added the search box to the ActionBar!
- Consider creating a static method in a Helper/Utility class for common methods such as checking for internet
- Consider adding [progress bars](http://guides.codepath.com/android/Handling-ProgressBars#actionbar-progress-bar) to your app whenever a network request goes out in addition to the placeholder images.

Also, here's a more detailed [Project 2 Feedback Guide here](http://courses.codepath.com/snippets/intro_to_android/project_2_feedback) which covers the most common issues with this submitted project. Read through the [feedback guide point-by-point](http://courses.codepath.com/snippets/intro_to_android/project_2_feedback) to determine how you could improve your submission. 

Let us know if you have any other thoughts or questions about this assignment. The next assignment (Twitter Client) will be especially important since it introduces the majority of the remaining pieces necessary to build a fully functional API client with complex feeds of data and user creation.
